// NOTE: This file is AUTO-GENERATED by the Safe Args Gradle plugin.
// It will be generated automatically when you build the project.
// It is included here only as a reference. Do NOT edit manually.
// Build the project in Android Studio to regenerate.

// The following safe args directions are available after build:
//
// HomeFragmentDirections.actionHomeFragmentToScannerFragment()
// HomeFragmentDirections.actionHomeFragmentToDetailFragment(receiptId: Int)
//
// ScannerFragmentDirections.actionScannerFragmentToConfirmationFragment(imagePath: String)
//
// ConfirmationFragmentDirections.actionConfirmationFragmentToHomeFragment()
//
// HistoryFragmentDirections.actionHistoryFragmentToDetailFragment(receiptId: Int)
//
// LoginFragmentDirections.actionLoginFragmentToHomeFragment()
// LoginFragmentDirections.actionLoginFragmentToSignupFragment()
//
// SignupFragmentDirections.actionSignupFragmentToHomeFragment()
